DROP TABLE poi;
CREATE TABLE poi(
  id VARCHAR,
  lon DECIMAL,
  lat DECIMAL,
  name VARCHAR,
  aerialway VARCHAR,
  aerodrome VARCHAR,
  aeroway VARCHAR,
  amenity VARCHAR,
  boundary VARCHAR,
  bridge VARCHAR,
  craft VARCHAR,
  emergency VARCHAR,
  heritage VARCHAR,
  highway VARCHAR,
  historic VARCHAR,
  junction VARCHAR,
  landuse VARCHAR,
  leisure VARCHAR,
  man_made VARCHAR,
  military VARCHAR,
  mountain_pass VARCHAR,
  "natural" VARCHAR,
  office VARCHAR,
  place VARCHAR,
  railway VARCHAR,
  shop VARCHAR,
  tourism VARCHAR,
  tunnel VARCHAR,
  waterway VARCHAR
);
